name: Historico Inventarios CSV

on:
  schedule:
    - cron: '0 6 * * *'  # 6 AM UTC (1 AM hora Colombia)
  workflow_dispatch:

env:
  API_TOKEN: ${{ secrets.API_TOKEN }}
  API_BASE_URL: ${{ secrets.API_BASE_URL }}

jobs:
  collect-data:
    runs-on: ubuntu-22.04
    timeout-minutes: 120  # Aumentar timeout por la paginación

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas requests

    - name: Run API collector
      run: python api_collector.py

    - name: List output files
      run: |
        echo "📂 Archivos generados:"
        ls -lh data/
        echo "📊 Tamaño de archivos CSV:"
        du -h data/*.csv

    - name: Commit and push data
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/
        git diff --quiet && git diff --staged --quiet || \
          (git commit -m "Auto-update: Historico Inventarios $(date +'%Y-%m-%d')" && git push)

    - name: Upload CSV as artifact
      uses: actions/upload-artifact@v4
      with:
        name: historico-inventarios-csv
        path: data/*.csv
        retention-days: 7
